# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter a genre name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(help_text='enter an image name', max_length=200)),
                ('date', models.DateField()),
                ('genre', models.ManyToManyField(help_text='select a genre for this image', to='myapp.Genre')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
