# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=myapp.models.Picture.get_upload_path)),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['imageName']},
        ),
    ]
